### ISSUE TITLE
Footer on mobile

### ISSUE THREAD

**Issue by aravindvnair99** [Diversity-In-DSC/dsc-webathon#58]
Would be better to have them in one line:

![image](https://user-images.githubusercontent.com/22199259/98950486-0d29f700-251f-11eb-9bf5-e593db249064.png)

**Comment by patelaryan7751** [comment]
can i work on this? @aravindvnair99

**Comment by aravindvnair99** [comment]
> can i work on this? @aravindvnair99

Thanks for your interest @patelaryan7751! :) This issue was fixed. Forgot to close it.

**Comment by aravindvnair99** [comment]
New repository: https://github.com/Diversity-In-DSC/DSC-WoW-Front-end
